### ISSUE TITLE
📝Next steps for Documentation

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#144]
As discussed in https://github.com/UNopenGIS/7/issues/137#issuecomment-1537808199: 

The following are tracked in [https://github.com/UNopenGIS/7-docs/issues/](https://github.com/UNopenGIS/7-docs/issues/):

- [ ] Focus on [Re-organizing `resources`](https://github.com/UNopenGIS/7-docs/issues/10)
- [ ] Complete [Smart Maps Bazaar event](https://github.com/UNopenGIS/7-docs/issues/8) page
- [ ] Broader level focus on `objective` of [Smart Maps](https://github.com/UNopenGIS/7-docs/issues/11)

**Comment by hfu** [comment]
#147 would be a part of this.

**Comment by hfu** [comment]
#274
