### ISSUE TITLE
UN Smart Maps Challenges / vientiane-landuse.pmtiles

### ISSUE THREAD

**Issue by hfu** [UNopenGIS/7#521]
## Background
- #487 
- #385 

## The basic idea
- UN Smart Challenges is the online and permanent continuation of the UN Crisis Map Challenge from the 7th Annual International Humanitarian Mapathon.
- Mapping challenges are regularly posted online, inviting anyone to participate in creating high-quality maps.
- We need to consider certificates or awards as incentives to encourage participation.

## TODO
- [ ] @hfu will be drafting some challenges from the context of international development. 
- [x] @albertkun will be considering how challenges should nicely be posted. 
- [ ] we may need ask advice from those who have contributed the last Annual International Humanitarian Mapathon.

**Comment by albertkun** [comment]
@hfu I created the challenges page on the smart maps website and called them `Smart Challenges` for now:

![image](https://github.com/UNopenGIS/7/assets/8574425/cf2c9125-e779-48ee-8f0b-9f38f18e4b5e)


I also created a template on hackmd.io to use for submitting challenges:

[![image](https://github.com/UNopenGIS/7/assets/8574425/37604b5c-5ffb-45cb-bb7d-8bdefcd5f154)](https://hackmd.io/@smartmaps/challenges)

**Comment by hfu** [comment]
@albertkun How nice! It looks to me a good start. 

I implemented 3 different styles for VirGo land use data. 

<img width="923" alt="image" src="https://github.com/UNopenGIS/7/assets/18297/e486ecaa-26e2-4a2b-840b-880cfd9c237d">

1. https://observablehq.com/d/096a07c4bdf3feb4
2. https://observablehq.com/d/bb8300cc6914ec28
3. https://observablehq.com/d/6922286c8dd156cf

They are not the actual challenge but some example, but we can try to move forward, if we can get help from colleagues who know well about how challenges should be implemented.

**Comment by yuiseki** [comment]
FOIL4Gで再現しました
- https://unopengis.github.io/foil4g/?path=/story/components-combined-vientianelandusemap--preview


ソースコード：
- https://github.com/UNopenGIS/foil4g/blob/main/src/components/Combined/VientianeLanduseMap/index.tsx
- https://github.com/UNopenGIS/foil4g/blob/main/src/components/Combined/VientianeLanduseMap/index.stories.ts

スクリーンレコード：
[![Image from Gyazo](https://i.gyazo.com/4fe5cf7823a2f1d87920633a752d97e8.gif)](https://gyazo.com/4fe5cf7823a2f1d87920633a752d97e8)

**Comment by yuiseki** [comment]
`Error with Permissions-Policy header: Origin trial controlled feature not enabled: 'interest-cohort'.`

これのせいか……？？？

**Comment by yuiseki** [comment]
https://optgeo.github.io/vientiane-landuse/vientiane-landuse.pmtiles をSource CooperativeにDeployしていただきたいです

**Comment by yuiseki** [comment]
いま見たら**何もしてないのに直ってました……**なんでやねん……

- https://unopengis.github.io/foil4g/?path=/story/components-combined-vientianelandusewithoverture--preview

**Comment by hfu** [comment]
GitHub Pages よりも Source Cooperative の方が信頼性が高そうな雰囲気がある、という経験が得られてよかったです。

Source Cooperative に smartmaps/foil4gr1 というリポジトリを作って、とりあえずデータをデプロイしていく場所にしたいと思います。X11R6 みたいに、Release 1 という意味を込めて r1 とつけるようにします。

smartmaps/foil4gr1/vientiane-landuse.pmtiles という名前になるようにデプロイしてみて、報告します。

**Comment by hfu** [comment]
アップロードしました！
https://beta.source.coop/smartmaps/foil4gr1/vientiane-landuse.pmtiles

<img width="1254" alt="image" src="https://github.com/UNopenGIS/7/assets/18297/6fe0838a-4558-4ce9-93bf-7c75dc35cf73">
